config/routes.rb
Cub::Application.routes.draw do

  resources :events
  resources :sessions
  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :end_date, :location, :name, :start_date, :url
  has_many :sessions
end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :location, :name, :start_time
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def access_token
    session[:access_token]
  end
  helper_method :access_token

end

app/controllers/auth_controller.rb
require "httparty"

class AuthController < ApplicationController

  SINGLY_API_BASE = "https://api.singly.com"

  def callback
    auth = request.env["omniauth.auth"]
    session[:access_token] = auth.credentials.token
    redirect_to "/"
  end

  def logout
    session.clear
    redirect_to "/"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @event = Event.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
    if access_token
      @profiles = HTTParty.get(profiles_url,
        :query => {:access_token => access_token}
      ).parsed_response
      puts "profile: #{@profiles}"
    end
  end

private

  def access_token
    session[:access_token]
  end
  helper_method :access_token

  SINGLY_API_BASE = "https://api.singly.com"

  def profiles_url
    "#{SINGLY_API_BASE}/profiles"
  end
end

app/controllers/login_page_controller.rb
class LoginPageController < ApplicationController
  def home
    if access_token
      @profiles = HTTParty.get(profiles_url,
        :query => {:access_token => access_token}
      ).parsed_response
      puts "profile: #{@profiles}"
    end
  end

private

  def access_token
    session[:access_token]
  end
  helper_method :access_token

  SINGLY_API_BASE = "https://api.singly.com"

  def profiles_url
    "#{SINGLY_API_BASE}/profiles"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /sessions
  # GET /sessions.json
  def index
    @sessions = Session.where(:event_id => params[:event_id]).map do |session|
      {
        name: session.name,
        start_time: session.start_time,
        location: session.location,
        link: session_path(session)
      }
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sessions }
    end
  end

  # GET /sessions/1
  # GET /sessions/1.json
  def show
    @session = Session.find(params[:id])
    @event = @session.event

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @session }
    end
  end

  # GET /sessions/new
  # GET /sessions/new.json
  def new
    @session = Session.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @session }
    end
  end

  # GET /sessions/1/edit
  def edit
    @session = Session.find(params[:id])
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @session = Session.new(params[:session])
    @session.event_id = params[:event_id]
    respond_to do |format|
      if @session.save
        format.html { redirect_to @session, notice: 'Session was successfully created.' }
        format.json { render json: @session, status: :created, location: @session }
      else
        format.html { render action: "new" }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sessions/1
  # PUT /sessions/1.json
  def update
    @session = Session.find(params[:id])

    respond_to do |format|
      if @session.update_attributes(params[:session])
        format.html { redirect_to @session, notice: 'Session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    @session = Session.find(params[:id])
    @session.destroy

    respond_to do |format|
      format.html { redirect_to sessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/login_page_helper.rb
module LoginPageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/_form.html.erb
<div class="modal-body">
  <%= form_for(@event, :html => {:class => 'form-horizontal'}) do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :description, :class => "modal-text-area" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :start_date, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :start_date, :type => "date" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :end_date, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :end_date, :type => "date" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :location, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :location %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :url, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :url %>
      </div>
    </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <button class="btn btn-primary">Save changes</button>
    </div>
  <% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<ul class="breadcrumb">
  <li><a href="#">Events</a> <span class="divider">/</span></li>
</ul>

<div class="content-area">

  <h1 text-align="center">CubNotes</h1>

  <table id="events-list" class="table table-bordered">
    <thead>
    <tr>
      <th>
        Event
      </th>
      <th>
        Location
      </th>
      <th>
        Dates
      </th>
    </tr>
    </thead>

    <% @events.each do |event| %>
      <tbody>
      <tr>
        <td>
          <%= link_to event.name, event_path(event) %>
        </td>
        <td>
          <%= event.location %>
        </td>
        <td>
          <%= event.start_date %> - <%= event.end_date %>
        </td>
      </tr>
      </tbody>
    <% end %>
  </table>

  <br/>
  <a href="#newEvent" role="button" class="btn" data-toggle="modal">New Event</a>
</div>

<div id="newEvent" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newEventLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="newEventLabel">New Event</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Events', root_path %><span class="divider">/</span></li>
  <li class="active"><%= @event.name%></li>
</ul>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Start date:</b>
  <%= @event.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @event.end_date %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Url:</b>
  <%= @event.url %>
</p>


<a href="#editEvent" role="button" class="btn" data-toggle="modal">Edit</a>

<div id="editEvent" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="editEventLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="editEventLabel">Edit Event</h3>
  </div>
  <%= render 'form' %>
</div>


<div ng-app="cub">
  <div ng-controller="SessionsController">

    <form ng-submit="addSession()">
      <label for="new_session_name">Create New Session:</label>
      <input id="new_session_name" type="text" ng-model="newSessionName" placeholder="Session Name">
      <input class="btn-primary" type="submit" value="add">
    </form>

    <div class="gridStyle" ng-grid="gridOptions"></div>

  </div>
</div>

app/views/home_page/index.html.erb
Events
<ul>
  <% Event.all.each do |event| %>
    <li>
      <%= event.name %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cub</title>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.4/angular.min.js"></script>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">

  <!-- Include Firebase -->
  <script src="https://cdn.firebase.com/v0/firebase.js"></script>
  <script src="/codemirror.js"></script>
  <link rel="stylesheet" href="/codemirror.css">
  <script src="/firepad.js"></script>
  <link rel="stylesheet" href="/firepad.css">
  <%= javascript_include_tag "application" %>
  <!-- Twitter Bootstrap -->
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css">
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


<% if Rails.env.production? %>
  <script>
    (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-41572754-1', 'cubnotes.net');
    ga('send', 'pageview');

  </script>
<% end %>
</body>
</html>

app/views/login_page/index.html.erb
<%= link_to("create", new_event_path) %>
Events
<ul>
  <% Event.all.each do |event| %>
    <li>
      <%= event.name %>
    </li>
  <% end %>
</ul>

app/views/login_page/login.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <script src="js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        <% if @profiles %>
            <p>Welcome back!</p>
        <% else %>
          <% if session[:access_token] %>
            <p>Log out</p>
          <% else %>
            <p>Please <%= link_to 'connect', '/auth/singly?service=linkedin' %> with LinkedIn</p>
          <% end %>
        <% end %>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='//www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>